name: Windows Compile

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build Visual Studio
        if: ${{ matrix.generate == 'Visual Studio 17 2022' }}
        run: |
          cmake -S . -B "build/${{ matrix.arch }}" -G "${{ matrix.generate }}" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain/${{ matrix.toolchain }}.cmake" -DCMAKE_GENERATOR_PLATFORM=${{ matrix.arch }} -DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }} -DUSE_STANDALONE=${{ matrix.standalone }}
          cmake --build ./build/${{ matrix.arch }}
      - name: Setup Variables
        if: ${{ matrix.generate == 'Ninja' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build Ninja
        if: ${{ matrix.generate == 'Ninja' }}
        run: |
          cmake -S . -B "build/${{ matrix.arch }}" -G "${{ matrix.generate }}" -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain/${{ matrix.toolchain }}.cmake" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }} -DUSE_STANDALONE=${{ matrix.standalone }}
          cmake --build ./build/${{ matrix.arch }}
      - name: Publish packaged artifacts
        if: ${{ matrix.config == 'Release' && matrix.generate == 'Visual Studio 17 2022' && matrix.standalone == 'ON' }}
        uses: actions/upload-artifact@v4
        with:
          name: torch-windows-${{ matrix.arch }}-${{ matrix.toolchain }}
          path: build/${{ matrix.arch }}/Release/torch.exe
